[book]
authors = ["Marcus Cvjeticanin", "Christopher Zeuch"]
title = "Njord"
description = "A lightweight ORM library in Rust with strong-typed SQL DSL and sequence API."
language = "en"
multilingual = false
git-repository-url = "https://github.com/njord-rs/docs"
git-repository-icon = "fa-github"
src = "src"
input-404 = "404.md"

[output.html]
copy-code = true

[build]
target-dir = "book"